on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
name: Wiki Sync
jobs:
    update-wiki:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - name: Sync Wiki
            uses: joeizzard/action-wiki-sync@master
            with:
                username: Cx01N
                access_token: ${{ secrets.GH_ACCESS_TOKEN }}
                wiki_folder: wiki
                commit_username: 'Cx01N'
