name: Wiki-Sync

on:
  push:
    branches: 
      - master

jobs:
  sync_docs:
    name: Sync docs
    runs-on: ubuntu-latest
    steps:
        - name: Checkout current version
          uses: actions/checkout@v2
        - name: Create files to sync
          run: |
            mkdir docs/
        - name: Sync with local action
          uses: kai-tub/external-repo-sync-action@v1
          with:
            repository: "Cx01N/empire-repo-wiki"
            source-directory: "./docs"
            include-patterns: "*.md"
            dry-run: true
          env:
            GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
