name: Wiki-Sync

on:
  push:
    branches: 
      - master

jobs:
  sync_docs:
    name: Sync docs
    runs-on: ubuntu-latest
    steps:
        - name: Sync with local action
          uses: kai-tub/external-repo-sync-action@v1
          with:
            repository: "Cx01N/empire-repo-wiki@master"
            source-directory: "./docs"
            include-patterns: "*.md"
          env:
            GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
