name: Wiki Sync

on:
  push:
    branches: 
      - master

jobs:
  sync_docs:
    name: Sync docs
    runs-on: ubuntu-latest
    steps:
        - name: Sync with local action
          uses: kai-tub/external-repo-sync-action@v1
          with:
            repository: "https://github.com/Cx01N/empire-repo-wiki"
          env:
            GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
